angular.module(`boilerPlate`)
  .controller(`siteCtrl`, require(`./siteCtrl`))
  .controller(`tournamentCtrl`, require(`./tournamentCtrl`))
  .controller(`newTournamentFormCtrl`, require(`./newTournamentFormCtrl`))
  .controller(`userDashboardCtrl`, require(`./userDashboardCtrl`))